- hosts: webserver
  tasks:
    - name: install pyhton-docker
      yum:
        name: python-docker
        state: present
      when:
        - ansible-distribution == "CentOS"
    - name: install pyhton-docker
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python-docker
      when:
        - ansible-distribution == "Ubuntu"
    - name: run container
      docker_container:
        name: apache2
        state: started
        image: ilhammasri/httpd:1
        published_ports:
          - 8081:80
        recreate: yes
